// svelte/src/App.svelte
<script lang="ts">
import Router from 'svelte-spa-router';
import { link } from 'svelte-spa-router';
import routes from './routes';
</script>

<main class="body">
  <div class="nav">
    <a href="/calc" use:link>calculator</a>
    <a href="/chat" use:link>chat</a>
    <a href="/landing" use:link>landing page</a>
    <a href="/signup" use:link>sign-up page</a>
    <a href="/todo" use:link>todo</a>
    <a href="/weather" use:link>weather</a>
  </div>
  <div class="route">
    <Router {routes} />
  </div> 
</main>

// vue/src/App.vue
<script lang="ts">
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
<main class="body">
  <div class="nav">
    <router-link to="/calc">calculator</router-link>
    <router-link to="/chat">chat</router-link>
    <router-link to="/landing">landing page</router-link>
    <router-link to="/signup">sign-up pager</router-link>
    <router-link to="/todo">todo</router-link>
    <router-link to="/weather">weather</router-link>
  </div>
  <div class="route">
    <RouterView />
  </div> 
</main> 
</template>
